name: Sort OpenAPI YAML

on:
  push:
    branches:
      - main

jobs:
  sort-yaml:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Stellt sicher, dass der Token Schreibzugriff hat

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2




    - name: Echo current directory
      run: |
        echo "Current directory:"
        pwd

    - name: List current directory contents
      run: |
        echo "Directory contents:"
        ls -la

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Run sorting script
      run: |
        python ./sortYaml/sortYaml.py

    - name: Commit sorted YAML file
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add sorted_openapi.yaml
        git commit -m 'Sort OpenAPI YAML file'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
